config/routes.rb
Rails.application.routes.draw do
  resources :enrolled_courses
  resources :courses do
    collection {post :import}
  end
  
  resources :users do
    collection {post :import}
  end

  resources :answers do
    member do
      put "like",    to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
  resources :questions do
    resources :answers
  end
  resources :forums do
    resources :questions  # add question routes
  end
  
  devise_for :users, :path_prefix => 'my', :controllers => { :registrations => 'registrations'}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users, only: [:show, :index, :edit, :update]
  
  get 'search', to: 'search#search'
  
  root to: "forums#index"
  
  

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :body, presence: true
  belongs_to :user
  belongs_to :forum
  has_many :answers
  def self.search(search)
    where("LOWER(body) LIKE ?", "%#{search.downcase}%")
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
    if params[:q]
      @questions = Question.search(params[:q]).order("created_at DESC")
    else
      @questions = Question.all.order("created_at DESC")
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @forum = Forum.find(params[:forum_id])
    @question = @forum.questions.new(question_params)
    @question.user = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to @forum, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { redirect_to @forum, notice: 'Question cannot be blank.' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to forum_url(@question.forum_id), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to forum_url(@question.forum_id), notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:forum_id, :body, :user_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body, :placeholder => "Enter question" %><br>
    <%= f.text_area :body, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
      <ul class="pager">
        <%= f.submit "Add Question", class: "btn btn-custom" %>
        <li class="next"><%= link_to 'Back', forums_path %></li>
      </ul>
  </div>
<% end %>

app/views/questions/_question.html.erb
<%= div_for(question) do %>
	<div class="link row clearfix">
		<div class="pull-left">
			<p class="lead"><%= link_to question.body, question %><br></p>
			<p><small>Submitted <strong><%= time_ago_in_words(question.created_at) %> ago</strong> by <%= question.user.name %></small></p>
		</div>
		<div class="btn-group pull-right">
			<% if current_user.try(:administrator?) %>
			    <%= link_to question, class: "btn btn-default btn-sm", title: "Delete question", method: :delete, data: { confirm: "Are you sure you want to delete this question?" } do %>
                    <i class="glyphicon glyphicon-trash"></i>
				<% end %>
			<% end %>
			<% if question.user == current_user -%>
			    <%= link_to edit_question_path(question), class: "btn btn-default btn-sm", title: "Edit question" do %>
                	<i class="glyphicon glyphicon-edit"></i>
   				<% end %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_url(@question.forum_id) %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<% if @questions.blank? %>
  <h4>There are no recipes containing the term <%= params[:q] %>.</h4>
<% end %>

<table>
  <thead>
    <tr>
      <th>Forum</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.forum_id %></td>
        <td><%= question.body %></td>
        <td><%= question.user %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<div class="page-header">
    <h1><%= @question.body %></h1>
</div>

<% if @question.user == current_user || current_user.try(:administrator?) -%>
	<div class="btn-group">
		<%= link_to edit_question_path(@question), class: "btn btn-default", title: "Edit question" do %>
      <i class="glyphicon glyphicon-edit"></i>
    <% end %>
    <%= link_to @question, class: "btn btn-default", title: "Delete question", method: :delete, data: { confirm: "Are you sure you want to delete this question?" } do %>
      <i class="glyphicon glyphicon-trash"></i>
    <% end %> 
	</div>
<% end %>

<h3 class="questions_title">
  <%= @question.answers.count %> Answers
</h3>

<div id="answers">
  <%= render :partial => @question.answers %>
</div>
<br>
<%= simple_form_for [@question, Answer.new]  do |f| %>
    <div class="field">
      <%= f.text_area :body, :placeholder => "Enter answer", autofocus: true,  class: "form-control" %>
    </div>
    <ul class="pager">
      <%= f.submit "Add Answer", class: "btn btn-custom" %>
      <li class="next"><%= link_to 'Back', forums_path %></li>
    </ul>
<% end %>