config/routes.rb
Rails.application.routes.draw do
  resources :enrolled_courses
  resources :courses do
    collection {post :import}
  end
  
  resources :users do
    collection {post :import}
  end

  resources :answers do
    member do
      put "like",    to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
  resources :questions do
    resources :answers
  end
  resources :forums do
    resources :questions  # add question routes
  end
  
  devise_for :users, :path_prefix => 'my', :controllers => { :registrations => 'registrations'}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users, only: [:show, :index, :edit, :update]
  
  get 'search', to: 'search#search'
  
  root to: "forums#index"
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  require 'csv'
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^name_/
      # Simple sort on the name colums
      order("LOWER(users.name) #{ direction }")
    end
  }
  scope :search_query, lambda { |query|
    # Searches the students table on the 'first_name' and 'last_name' columns.
    # Matches using LIKE, automatically appends '%' to each term.
    # LIKE is case INsensitive with MySQL, however it is case
    # sensitive with PostGreSQL. To make it work in both worlds,
    # we downcase everything.
    return nil  if query.blank?
  
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
  
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conds = 1
    where(
      terms.map { |term|
        "(LOWER(users.name) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }
  # Association link between users and forums       
  has_many :forums
  has_many :answers
  has_many :enrolled_courses
  has_many :courses, :through => :enrolled_courses
  filterrific(
    default_filter_params: { sorted_by: 'name' },
    available_filters: [
        :sorted_by,
        :search_query
    ]
  )
  def increase_reputation(count=1)
    update_attribute(:reputation, reputation + count)
  end
  
  def decrease_reputation(count=1)
    update_attribute(:reputation, reputation - count)
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      User.create! row.to_hash
    end
  end
  
  def timeout_in
    return 1.days
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_filter :authenticate_user!

    
    def show
        @user = User.find(params[:id]) 
    end
    
    def index
       # @users = User.paginate(:page => params[:page], :per_page => 5)
        @filterrific = initialize_filterrific(
            User,
            params[:filterrific]
        )
        @users = @filterrific.find.page(params[:page]).paginate(:page => params[:page], :per_page => 5) 
    end
    
    def import
        User.import(params[:file])
        redirect_to :back, notice: "Users were successfully imported"
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        if @user.destroy
           redirect_to root_path, notice: "User was successfully deleted."
        end   
    end
    
    def edit
        @user = User.find(params[:id])
    end
    
   def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to users_path, notice: "User was successfully updated."
        else
            format.html { render :edit }
        end
   end
    
    def user_params
        params.require(:user).permit(:name, :email, :faculty, :administrator)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_index.html.erb
<div class="containter">
    <div class="row">
        <div class="col-lg-12">
            <div class="main-box no-header clearfix">
                <div class="main-box-body clearfix">
                    <div class="table-responsive">
                        <table class="table user-list">
                            <thead>
                                <tr>
                                <th><span>User</span></th>
                                <th><span>Created</span></th>
                                <th><span>Reputation</span></th>
                                <th><span>Email</span></th>
                                <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <% @users.each do |user| %>
                                <tbody>
                                    <tr>
                                        <td>
                                            <img src="/NKU_CMYK_D.gif" alt="">
                                            <div class="user-link">
                                                <%= link_to user.name, user_path(user) %>
                                            </div>
                                            <span class="user-subhead">
                                                <% if user.administrator? %>
                                                    Administrator
                                                <% elsif user.faculty? %>
                                                    Faculty
                                                <% else %>
                                                    Student
                                                <% end %> 
                                            </span>
                                        </td>
                                        <td><%= user.created_at %></td>
                                        <td><%= user.reputation %></td>
                                        <td><%= user.email %></td>
                                        <td>
                                            <div class="btn btn-sm btn-warning" data-toggle="tooltip" title="edit user">
                                                <%= link_to edit_user_path(user) do %>
                                				    <i class="glyphicon glyphicon-edit"></i>
                                			    <% end %>
                                            </div>
                                            <div class="btn btn-sm btn-danger" data-toggle="tooltip" title="delete user">
                                    			<%= link_to admin_destroy_user_path(user), method: :delete, data: { confirm: "Are you sure?" } do %>
                                    				<i class="glyphicon glyphicon-remove"></i>
                                    			<% end %>
                                			</div>
                                    	</td>
                                	</tr>
                                	<script>
                                        $(document).ready(function(){
                                            $('[data-toggle="tooltip"]').tooltip(); 
                                        });
                                    </script>
                                </tbody>
                            <% end %>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>   
<%= will_paginate @users, render: BootstrapPagination::Rails, :class => "digg_pagination center" %>
<br><br>
<div class="btn btn-custom" data-toggle="tooltip" title="Create a single user">
    <%= link_to "Add User", new_user_registration_path %>
</div>
<br>
<h5>Import Users</h5>
    <%= form_tag import_users_path, multipart: true do %>
        <%= file_field_tag :file %><br>
        <%= submit_tag "Import CSV" %>
    <% end %>

app/views/users/_admin_show.html.erb
<div class="makeCenter">
    <figure class="snip0057 gold">
      <figcaption>
        <h2><span><%= @user.name %></span></h2>
        <p>
            <%= @user.email %><br>
            User reputation of <%= @user.reputation %><br>
            Course list<br><% @user.courses.each do |c| %><%= link_to c.name, course_path(c) %><br><% end %>
        </p>
        <div class="icons"><%= link_to edit_user_path(@user), class: "btn btn-sm", title: "Edit user" do %>
          <i class="glyphicon glyphicon-edit"></i>
        <% end %>
        <%= link_to admin_destroy_user_path(@user), class: "btn btn-sm", title: "Delete user", method: :delete, data: { confirm: "Are you sure you want to delete this forum?" } do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>   </div>
      </figcaption>
      <div class="image"><img <%=image_tag("NKU1.jpg")%> alt="NKU1"/></div>
        <div class="position">
            <% if @user.administrator? %>
                Administrator
            <% elsif @user.faculty? %>
                Faculty
            <% else %>
                Student
            <% end %>
        </div>
    </figure>   
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :user_type %><br>
    <%= f.text_field :user_type %>
  </div>
  <div class="field">
    <%= f.label :reputation %><br>
    <%= f.text_field :reputation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Edit</h2>

<%= form_for(@user) do |f| %>

  <div class="panel panel-default">
    <div class="panel-body">
      <div class="form-inputs">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", :autofocus => true %>
        </div>
  
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control", :autofocus => true %>
        </div>
        
    	<div class="form-group">
      		<div><%= f.check_box :administrator, {}, true, false %> <%= f.label :administrator, "Administrator" %> </div>
          <div><%= f.check_box :faculty, {}, true, false %> <%= f.label :faculty, "Faculty" %> </div>
    	</div>
      </div>

      <div class="form-group">
        <%= f.submit "Update", class: "btn btn-custom" %>
      </div>

    <% end %>
  </div>
  <div class="panel-footer">
    <%= link_to admin_destroy_user_path(@user), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="glyphicon glyphicon-remove"></i> Destroy account
    <% end %>  
  </div>

app/views/users/index.html.erb
<div>
    <div class="container" style="padding-bottom: 10px">
            <%= form_for_filterrific @filterrific do |f| %>
                  <div>
                    Search
                    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
                    <%= f.text_field(
                      :search_query,
                      class: 'filterrific-periodically-observed'
                    ) %>
                  </div>
            <% end %>
    </div>
    <div class="makeCenter">
        <div class="container">
            <% if current_user.administrator? -%>
                <%= render 'admin_index' %>
            <% else %>
                    <div class="row">
                    <div class="col-lg-12">
                        <div class="main-box no-header clearfix">
                            <div class="main-box-body clearfix">
                                <div class="table-responsive">
                                    <table class="table user-list">
                                        <thead>
                                            <tr>
                                            <th><span>User</span></th>
                                            <th><span>Reputation</span></th>
                                            <th><span>Email</span></th>
                                            <th>&nbsp;</th>
                                            </tr>
                                        </thead>
                                        <% @users.each do |user| %>
                                            <% if not user.administrator %>
                                                <tbody>
                                                    <tr>
                                                        <td>
                                                            <img src="/NKU_CMYK_D.gif" alt="">
                                                            <div class="user-link">
                                                                <%= link_to user.name, user_path(user) %>
                                                            </div>
                                                            <span class="user-subhead">
                                                                <% if user.administrator? %>
                                                                    Administrator
                                                                <% elsif user.faculty? %>
                                                                    Faculty
                                                                <% else %>
                                                                    Student
                                                                <% end %> 
                                                            </span>
                                                        </td>
                                                        <td><%= user.reputation %></td>
                                                        <td><%= user.email %></td>
                                                	</tr>
                                                	<script>
                                                        $(document).ready(function(){
                                                            $('[data-toggle="tooltip"]').tooltip(); 
                                                        });
                                                    </script>
                                                </tbody>
                                            <% end %>
                                        <% end %>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <%= will_paginate @users, render: BootstrapPagination::Rails, :class => "digg_pagination center" %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% if current_user.administrator? -%>
    <%= render 'admin_show' %>
<% else %>
    <div class="makeCenter">
         <figure class="snip0057 gold">
        <figcaption>
        <h2><span><%= @user.name %></span></h2>
        <p>
            <%= @user.email %><br>
            User reputation of <%= @user.reputation %><br>
            Course list<br><% @user.courses.each do |c| %><%= link_to c.name, course_path(c) %><br><% end %>
        </p>
        <br>
        <div class="icons"></div>
        </figcaption>
            <div class="image"><img <%=image_tag("NKU1.jpg")%> alt="NKU1"/></div>
            <div class="position">
                <% if @user.administrator? %>
                    Administrator
                <% elsif @user.faculty? %>
                    Faculty
                <% else %>
                    Student
                <% end %>
            </div>
        </figure> 
    </div>
<% end %>