config/routes.rb
Rails.application.routes.draw do
  resources :enrolled_courses
  resources :courses do
    collection {post :import}
  end
  
  resources :users do
    collection {post :import}
  end

  resources :answers do
    member do
      put "like",    to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
  resources :questions do
    resources :answers
  end
  resources :forums do
    resources :questions  # add question routes
  end
  
  devise_for :users, :path_prefix => 'my', :controllers => { :registrations => 'registrations'}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users, only: [:show, :index, :edit, :update]
  
  get 'search', to: 'search#search'
  
  root to: "forums#index"
  
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :body, presence: true
  acts_as_votable
  belongs_to :user
  belongs_to :question
  
  # Order answers by votes
  default_scope {
    order(cached_votes_up: :desc)
  }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { redirect_to @question, notice: 'Answer cannot be blank.' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to question_url(@answer.question_id), notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { redirect_to edit_answer_path, notice: 'Updated answer cannot be blank.' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_url(@answer.question_id), notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @answer = Answer.find(params[:id])
    @answer.upvote_by current_user
    @answer.user.increase_reputation
    respond_to do |format|
        format.html {redirect_to :back }
        format.json { render json: { count: @answer.get_upvotes.size } }
    end
  end
  
  def downvote
    @answer = Answer.find(params[:id])
    @answer.downvote_by current_user
    @answer.user.decrease_reputation
    respond_to do |format|
        format.html {redirect_to :back }
        format.json { render json: { count: @answer.get_downvotes.size } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :body, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<%= div_for(answer) do %>
	<div class="link row clearfix">
		<div class="row">
			<div class="col-md-6">
				<p class="lead"><%= answer.body %><br></p>
				<p><small>Submitted <strong><%= time_ago_in_words(answer.created_at) %> ago</strong> by <%= answer.user.name %></small></p>
			</div>
			<div class="btn-group pull-right">
				<% if current_user.try(:administrator?) %>
					<%= link_to answer, class: "btn btn-default btn-sm", title: "Delete answer", method: :delete, data: { confirm: "Are you sure you want to delete this answer?" } do %>
                        <i class="glyphicon glyphicon-trash"></i>
 					<% end %> 
				<% end %>
				<% if answer.user == current_user -%>
				    <%= link_to edit_answer_path(answer), class: "btn btn-default btn-sm", title: "Edit answer" do %>
                            <i class="glyphicon glyphicon-edit"></i>
                    <% end %>
				<% end %>
				<%= link_to like_answer_path(answer), class:'vote', method: :put, remote: true, class: "btn btn-default btn-sm",  rel: "tooltip", title: "Upvote" do %>
			      <span class="glyphicon glyphicon-arrow-up"></span>
			      <%= answer.get_upvotes.size %>
			    <% end %>
			    <%= link_to dislike_answer_path(answer), class:'vote', method: :put, remote: true, class: "btn btn-default btn-sm", rel: "tooltip", title: "Downvote" do %>
			      <span class="glyphicon glyphicon-arrow-down"></span>
			      <%= answer.get_downvotes.size %>
			    <% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body, :placeholder => "Enter answer" %>
    <%= f.text_area :body, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Add Answer", class: "btn btn-custom" %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', question_url(@answer.question_id) %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question_id %></td>
        <td><%= answer.body %></td>
        <td><%= answer.user %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>