config/routes.rb
Rails.application.routes.draw do
  resources :enrolled_courses
  resources :courses do
    collection {post :import}
  end
  
  resources :users do
    collection {post :import}
  end

  resources :answers do
    member do
      put "like",    to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
  resources :questions do
    resources :answers
  end
  resources :forums do
    resources :questions  # add question routes
  end
  
  devise_for :users, :path_prefix => 'my', :controllers => { :registrations => 'registrations'}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users, only: [:show, :index, :edit, :update]
  
  get 'search', to: 'search#search'
  
  root to: "forums#index"
  
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.nku.edu">NKU</a> question/answer forum.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "NKUNet", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
        <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Courses", :courses %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
         <% else %>
          <li><%= link_to "Log in", login_path %></li>
         <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NKUNET</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-inner">
      
      <div class="container">
        <div id="logo" class="navbar-brand">
        <%= link_to image_tag("nkunet.png"), root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
        	<% if user_signed_in? -%>
						<ul class="nav navbar-nav navbar-right">
						  <li><%= link_to "Home", root_path, :class => 'nav_links' %></li>
							<li><%= link_to 'Users', users_path %></li>
							<li><%= link_to 'Courses', courses_path %></li>
              <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'My Profile', current_user %></li>
                    <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                    <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                  </ul>
              </li>
              <li>
                 <%= link_to search_path do %>
                      <i class="glyphicon glyphicon-search"></i>
                 <% end %>
              </li>
						</ul>
					<% else -%>
						<ul class="nav navbar-nav navbar-right">
						  <li><%= link_to 'Sign in', new_user_session_path %></li>
						  <li>
                 <%= link_to search_path do %>
                      <i class="glyphicon glyphicon-search"></i>
                 <% end %>
              </li>
						</ul>
					<% end -%>
        </nav>
      </div>
    </div>
  </header>
	<div id="main_content" class="container">
		<% flash.each do |name, msg| %>
		  <% unless name.to_s == 'timedout' %>
		    	  <%= content_tag(:div, msg, class: "alert alert-info") %>
		  <% end %>
		<% end %>
		<div id="content" class="col-md-9 center-block">
				<%= yield %>
		</div>
	</div>
</body>	
<footer class="footer">
  <div class="container">
  	<div class="col-sm-8 col-sm-offset-2 text-center">
      <hr>
      <h3>
        About NKUNET
      </h3>
      <p>NKUNet is a platform for students at <a href="https://nku.edu">NKU</a> to get answers to their questions.</p>
      <hr>
      <ul class="list-inline center-block">
        <h3>Around the web</h3>
      	<li><a href="https://www.facebook.com/nkuedu/"><i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i></a></li>
      	<li><a href="https://plus.google.com/111072118272929485955"><i class="fa fa-google-plus-official fa-2x" aria-hidden="true"></i></a></li>
        <li><a href="https://www.instagram.com/nkuedu/?hl=en"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></li>
        <li><a href="https://twitter.com/nkuedu?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></a></li>
        <li><a href="https://github.com/stulzm2/nkunet"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a></li>
        <li><a href="https://www.youtube.com/user/nku"><i class="fa fa-youtube-square fa-2x" aria-hidden="true"></i></a></li>
        <li><a href="https://www.tumblr.com/tagged/nku"><i class="fa fa-tumblr fa-2x" aria-hidden="true"></i></a></li>
        <li><a href="https://www.pinterest.com/explore/northern-kentucky-university/"><i class="fa fa-pinterest fa-2x" aria-hidden="true"></i></a></li>
        <li><a href="https://www.linkedin.com/edu/northern-kentucky-university-18406"><i class="fa fa-linkedin fa-2x" aria-hidden="true"></i></a></li>
      </ul>
      <p>Copyright © NKUNet 2017</p>
    </div><!--/col-->
    <ul class="nav pull-right scroll-top">
  <li><a href="#" title="Scroll to top"><i class="glyphicon glyphicon-chevron-up"></i></a></li>
  </div><!--/container-->
  
</ul>
</footer>

</html>